VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "slangGetIcalHolidayType"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'//
'// slangGetIcalHolidayType.cls
'//
'// Created by slangsoft on 2015/01/25.
'// Copyright (c) 2015 Slang Software. All rights reserved.
'//
Option Explicit

Public hName As String
Public hDate As String
